name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
    - uses: ./
