name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Spell checking
    permissions:
      checks: write
      issues: write
      contents: read
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: check-spelling
      id: spelling
      uses: ./
      with:
        experimental_apply_changes_via_bot: 1
    - name: store-comment
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: "check-spelling-comment-${{ github.run_id }}"
        path: |
          ${{ steps.spelling.outputs.skipped_files }}
          ${{ steps.spelling.outputs.stale_words }}
          ${{ steps.spelling.outputs.unknown_words }}
          ${{ steps.spelling.outputs.suggested_dictionaries }}
          ${{ steps.spelling.outputs.warnings }}

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: spelling
    if: always() && needs.spelling.result == 'failure'
    steps:
    - name: retrieve-comment
      uses: actions/download-artifact@v2
      with:
        name: "check-spelling-comment-${{ github.run_id }}"

    - name: checkout
      uses: actions/checkout@v2
    - name: comment
      run:
        cat tokens.txt


  update:
    name: Update PR
    permissions:
      checks: write
      issues: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '@check-spelling-bot apply')
      }}
    steps:
    - name: checkout-merge
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: check-spelling
      uses: ./
      with:
        experimental_apply_changes_via_bot: 1
